apiVersion: v1
kind: Service
metadata:
  name: devops-demo
  labels:
    name: devops-demo
    app: devops-demo
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer
  selector:
     name: devops-demo
     app: devops-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo
  labels:
    app: devops-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: devops-demo
      app: devops-demo
  template:
    metadata:
      name: devops-demo
      labels:
        name: devops-demo
        app: devops-demo

    spec:
      containers:
      - name: devops-demo
        image: gcr.io/parabolic-rope-278721/devops-demo
        imagePullPolicy: Always
        ports:
        - containerPort: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: devops-demo
  namespace: default
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: devops-demo
  targetCPUUtilizationPercentage: 80

